---
- name: Add elasticsearch repository
  yum_repository:
    name: elasticsearch-5.x
    description: elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Add Elasticsearch key to keystore
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Install Metricbeat
  yum:
    name: metricbeat
    state: latest
- name: Configure metricbeat to collect docker stats
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify: "notify metricbeat for restart"
- name: Configure Dashboard if deploy_dashboard has been set in vars
  lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    line: "dashboards.enabled: true"
  notify: "notify metricbeat for restart"
  when: deploy_dashboard | bool
